version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      dev-dependencies-minor-patch:
        dependency-type: development
        update-types:
          - minor
          - patch